### ISSUE TITLE
主板的HDMI没有驱动是不是意味着核显用户没发用

### ISSUE THREAD

**Issue by dev-wwj** [GaryOAO/MSI-Z390i-hackintosh-clover#1]

**Comment by dev-wwj** [comment]
主板 msi-z390i GAMING EDGE AC,  cpu 9600k, 没有独显

**Comment by GaryOAO** [comment]
我忘记了这个有没有打缓冲帧，你可以用hackintool打一下缓冲帧试一下，因为我用的是vega56，所以就没有去折腾这个，等一下我会给config.plist更新一下，加入我打的iMac,19,2的缓冲帧。核显用户应该是可以使用主板的dp接口（手边没有DP显示器，没法测试）。HDMI应该是需要定制的，你可以参考黑果小兵的博客里HDMI的定制，后期我可能会自己研究定制一下主板的HDMI，如果定制成功了我会更新。

**Comment by LianYangCn** [comment]
我尝试了一下，没有成功，始终只能驱动DP，黑果小兵的HDMI定制，和英文原版，都看了，也试了一下，没出来

**Comment by GaryOAO** [comment]
> 我尝试了一下，没有成功，始终只能驱动DP，黑果小兵的HDMI定制，和英文原版，都看了，也试了一下，没出来

远景上有一个使用opencore驱动hdmi的，你可以研究一下那个efi，标题：微星z390刀锋oc引导几乎完美EFI

**Comment by LianYangCn** [comment]
> > 我尝试了一下，没有成功，始终只能驱动DP，黑果小兵的HDMI定制，和英文原版，都看了，也试了一下，没出来
> 
> 远景上有一个使用opencore驱动hdmi的，你可以研究一下那个efi，标题：微星z390刀锋oc引导几乎完美EFI

这个是 z390 不是 z390i ，但即便是这样我也试了，结果发现，可以正常启动，但是部分USB口不能用，网卡不能用，HDMI 也不能用

**Comment by LianYangCn** [comment]
> > 我尝试了一下，没有成功，始终只能驱动DP，黑果小兵的HDMI定制，和英文原版，都看了，也试了一下，没出来
> 
> 远景上有一个使用opencore驱动hdmi的，你可以研究一下那个efi，标题：微星z390刀锋oc引导几乎完美EFI

我试了一下，不行，z390 和 z390i 差别有那么大吗？

**Comment by GaryOAO** [comment]
> > > 我尝试了一下，没有成功，始终只能驱动DP，黑果小兵的HDMI定制，和英文原版，都看了，也试了一下，没出来
> > 
> > 
> > 远景上有一个使用opencore驱动hdmi的，你可以研究一下那个efi，标题：微星z390刀锋oc引导几乎完美EFI
> 
> 这个是 z390 不是 z390i ，但即便是这样我也试了，结果发现，可以正常启动，但是部分USB口不能用，网卡不能用，HDMI 也不能用

HDMI核显输出已解决，请移步至[OpenCore版本](https://github.com/GaryOAO/MSI-Z390i-hackintosh-OpenCore)
