### ISSUE TITLE
对硬盘有要求吗我的是pm981

### ISSUE THREAD

**Issue by happywzl** [GaryOAO/MSI-Z390i-hackintosh-clover#2]

**Comment by GaryOAO** [comment]
pm981需要打补丁，可以自己在网上查教程。个人建议最好换一个硬盘





------------------ 原始邮件 ------------------
发件人: happywzl <notifications@github.com&gt;
发送时间: 2020年4月12日 07:23
收件人: GaryOAO/MSI-Z390i-hackintosh-clover <MSI-Z390i-hackintosh-clover@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[GaryOAO/MSI-Z390i-hackintosh-clover] 对硬盘有要求吗我的是pm981 (#2)

**Comment by GaryOAO** [comment]
pm981需要打补丁，可以自己在网上查教程。个人建议最好换一个硬盘

**Comment by happywzl** [comment]
谢谢，我重新买了个c2000 pro，等到货。还有一个问题啊，您用的是什么我想网卡，这个主板背面的m2是插硬盘的,并不是M2wifi

**Comment by GaryOAO** [comment]
我暂时对WiFi没有要求所以就没有买网卡，这个主板的自带网卡不能换成DW1802那样的卡（因为这个板子只支持CNVI协议），所以只能占用一个M.2接口用一块转接板接上白果的免驱卡，所以你的选择只有94360系列（推荐BCM94360CD注意要买四天线的，这样2.4Ghz和蓝牙才不会互相干扰）

**Comment by happywzl** [comment]
> 我暂时对WiFi没有要求所以就没有买网卡，这个主板的自带网卡不能换成DW1802那样的卡（因为这个板子只支持CNVI协议），所以只能占用一个M.2接口用一块转接板接上白果的免驱卡，所以你的选择只有94360系列（推荐BCM94360CD注意要买四天线的，这样2.4Ghz和蓝牙才不会互相干扰）

谢谢大神，我今天看了很久，你太专业了，确实是这样，替换不了原来网卡，只能用m2转接。感谢建议

**Comment by GaryOAO** [comment]
> > 我暂时对WiFi没有要求所以就没有买网卡，这个主板的自带网卡不能换成DW1802那样的卡（因为这个板子只支持CNVI协议），所以只能占用一个M.2接口用一块转接板接上白果的免驱卡，所以你的选择只有94360系列（推荐BCM94360CD注意要买四天线的，这样2.4Ghz和蓝牙才不会互相干扰）
> 
> 谢谢大神，我今天看了很久，你太专业了，确实是这样，替换不了原来网卡，只能用m2转接。感谢建议

过奖了，共同学习

**Comment by GaryOAO** [comment]
> > 我暂时对WiFi没有要求所以就没有买网卡，这个主板的自带网卡不能换成DW1802那样的卡（因为这个板子只支持CNVI协议），所以只能占用一个M.2接口用一块转接板接上白果的免驱卡，所以你的选择只有94360系列（推荐BCM94360CD注意要买四天线的，这样2.4Ghz和蓝牙才不会互相干扰）
> 
> 谢谢大神，我今天看了很久，你太专业了，确实是这样，替换不了原来网卡，只能用m2转接。感谢建议

过奖了，共同学习
