### ISSUE TITLE
目录结构

### ISSUE THREAD

**Issue by CornM** [GaryOAO/MSI-Z390i-hackintosh-clover#5]
请教一个问题，这个目录直接复制到CLOVER文件夹使用么

**Comment by GaryOAO** [comment]
是的，直接覆盖就可以

**Comment by CornM** [comment]
> 
> 是的，直接覆盖就可以

谢了

**Comment by CornM** [comment]
可能会遇到  ‘This Version of Mac OS X is not supported on this platform!'问题，解决方法:
在启动参数中增加 -no_compat_check

**Comment by GaryOAO** [comment]
这是没有添加smbios信息的原因，用clover configurator生成smbios信息后删除引导项重启即可，感谢反馈。
